import './js/api/BooksApiService';
import './js/modals/modal';
import './js/modals/auth-modal';
import './js/other/scroll-up';
import './js/dark-theme/darkTheme';
import './js/shopping-list/ShoppingList';
import './js/header/header';
import './js/support/support';
import './js/firebase/auth';
