import './js/fetchBooks';
import './js/modals/modal';
import './js/auth-modal';
import './js/scroll-up';
import './js/darkTheme';
import './js/shopping-list/getShoppingList';
import './js/header/header';
import './js/support/support';
import './js/auth';
